# Generated by Django 3.1.5 on 2021-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='currenttown',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='friend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='hometown',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='qualification',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='relationship',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='work',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
